// © 2025 Software Company Co., Ltd. All rights reserved.
//
  // * author : KarmanMajd * //
  // * company : Software Company Co., Ltd. * //
  // * MIT License : https://opensource.org/licenses/MIT * //
  // * script type : sc app html dom head autowriter script * //
  // * This script is protected by copyright law. Unauthorized use or distribution is prohibited. * //
  // * version : 2.1.0 * //
  // * realease : 2025 * //
//
fetch('https://api.ipify.org?format=json').then(response=>response.json()).then(data=>{const ip=data.ip;const meta=document.createElement('meta');meta.name='ip';meta.content=ip;document.head.appendChild(meta);});
const scmasappnameconfiginit=document.createElement('meta');scmasappnameconfiginit.name='application-name';scmasappnameconfiginit.content='Software Company';document.head.appendChild(scmasappnameconfiginit);
const scmssuappconfiginit=document.createElement('meta');scmssuappconfiginit.name='msapplication-starturl';scmssuappconfiginit.content='https://softwarecompanycoltd.pages.dev/';document.head.appendChild(scmssuappconfiginit);
const scmstitleappconfiginit=document.createElement('meta');scmstitleappconfiginit.name='msapplication-TileColor';scmstitleappconfiginit.content='#F4F4F4';document.head.appendChild(scmstitleappconfiginit);
const scmsimageappconfiginit=document.createElement('meta');scmsimageappconfiginit.name='msapplication-TileImage';scmsimageappconfiginit.content='../root/favicon/Software-Company-New-Logo-with-no-background-minimal.png';document.head.appendChild(scmsimageappconfiginit);
const scmsapptooltipconfiginit=document.createElement('meta');scmsapptooltipconfiginit.name='msapplication-tooltip';scmsapptooltipconfiginit.content='Launch Software Company';document.head.appendChild(scmsapptooltipconfiginit);
const scusripadresscollect=document.createElement('script');scusripadresscollect.src='https://api.ipify.org?format=json';scusripadresscollect.type='application/ld+json';scusripadresscollect.async=true;document.head.appendChild(scusripadresscollect);
const scappmainmanifset=document.createElement('link');scappmainmanifset.href='./manifest.json';scappmainmanifset.rel='manifest';document.head.appendChild(scappmainmanifset);
const scgtminit=document.createElement('script');scgtminit.src='https://www.googletagmanager.com/gtag/js?id=G-HYC0R2MY88';scgtminit.type='text/javascript';scgtminit.async=true;document.head.appendChild(scgtminit);
const scappmainicon=document.createElement('link');scappmainicon.rel='shortcut icon';scappmainicon.type='image/x-icon';scappmainicon.href='../root/favicon/Software-Company-New-Logo-with-no-background-minimal.png';document.head.appendChild(scappmainicon);
const scappmainiiconi16=document.createElement('link');scappmainiiconi16.rel='icon';scappmainiiconi16.sizes='16x16';scappmainiiconi16.href='./../cdn.softwarecompany.static.com/icons/webapp/16px/logo.png';document.head.appendChild(scappmainiiconi16);
const scappmainiiconi32=document.createElement('link');scappmainiiconi32.rel='icon';scappmainiiconi32.sizes='32x32';scappmainiiconi32.href='./../cdn.softwarecompany.static.com/icons/webapp/32px/logo.png';document.head.appendChild(scappmainiiconi32);
const scappmainiiconi60=document.createElement('link');scappmainiiconi60.rel='icon';scappmainiiconi60.sizes='60x60';scappmainiiconi60.href='./../cdn.softwarecompany.static.com/icons/webapp/60px/logo.png';document.head.appendChild(scappmainiiconi60);
const scappmainiiconi64=document.createElement('link');scappmainiiconi64.rel='icon';scappmainiiconi64.sizes='64x64';scappmainiiconi64.href='./../cdn.softwarecompany.static.com/icons/webapp/64px/logo.png';document.head.appendChild(scappmainiiconi64);
const scappmainiiconi90=document.createElement('link');scappmainiiconi90.rel='icon';scappmainiiconi90.sizes='90x90';scappmainiiconi90.href='./../cdn.softwarecompany.static.com/icons/webapp/90px/logo.png';document.head.appendChild(scappmainiiconi90);
const scappmainiiconi128=document.createElement('link');scappmainiiconi128.rel='icon';scappmainiiconi128.sizes='128x128';scappmainiiconi128.href='./../cdn.softwarecompany.static.com/icons/webapp/128px/logo.png';document.head.appendChild(scappmainiiconi128);
const scappmainiiconi192=document.createElement('link');scappmainiiconi192.rel='icon';scappmainiiconi192.sizes='192x192';scappmainiiconi192.href='./../cdn.softwarecompany.static.com/icons/webapp/192px/logo.png';document.head.appendChild(scappmainiiconi192);
const scappmainiiconi512=document.createElement('link');scappmainiiconi512.rel='icon';scappmainiiconi512.sizes='512x512';scappmainiiconi512.href='./../cdn.softwarecompany.static.com/icons/webapp/512px/logo.png';document.head.appendChild(scappmainiiconi512);
const scappmainatiiconi16=document.createElement('link');scappmainatiiconi16.rel='apple-touch-icon';scappmainatiiconi16.sizes='16x16';scappmainatiiconi16.href='./../cdn.softwarecompany.static.com/icons/webapp/16px/logo.png';document.head.appendChild(scappmainatiiconi16);
const scappmainatiiconi32=document.createElement('link');scappmainatiiconi32.rel='apple-touch-icon';scappmainatiiconi32.sizes='32x32';scappmainatiiconi32.href='./../cdn.softwarecompany.static.com/icons/webapp/32px/logo.png';document.head.appendChild(scappmainatiiconi32);
const scappmainatiiconi60=document.createElement('link');scappmainatiiconi60.rel='apple-touch-icon';scappmainatiiconi60.sizes='60x60';scappmainatiiconi60.href='./../cdn.softwarecompany.static.com/icons/webapp/60px/logo.png';document.head.appendChild(scappmainatiiconi60);
const scappmainatiiconi64=document.createElement('link');scappmainatiiconi64.rel='apple-touch-icon';scappmainatiiconi64.sizes='64x64';scappmainatiiconi64.href='./../cdn.softwarecompany.static.com/icons/webapp/64px/logo.png';document.head.appendChild(scappmainatiiconi64);
const scappmainatiiconi90=document.createElement('link');scappmainatiiconi90.rel='apple-touch-icon';scappmainatiiconi90.sizes='90x90';scappmainatiiconi90.href='./../cdn.softwarecompany.static.com/icons/webapp/90px/logo.png';document.head.appendChild(scappmainatiiconi90);
const scappmainatiiconi128=document.createElement('link');scappmainatiiconi128.rel='apple-touch-icon';scappmainatiiconi128.sizes='128x128';scappmainatiiconi128.href='./../cdn.softwarecompany.static.com/icons/webapp/128px/logo.png';document.head.appendChild(scappmainatiiconi128);
const scappmainatiiconi192=document.createElement('link');scappmainatiiconi192.rel='apple-touch-icon';scappmainatiiconi192.sizes='192x192';scappmainatiiconi192.href='./../cdn.softwarecompany.static.com/icons/webapp/192px/logo.png';document.head.appendChild(scappmainatiiconi192);
const scappmainatiiconi512=document.createElement('link');scappmainatiiconi512.rel='apple-touch-icon';scappmainatiiconi512.sizes='512x512';scappmainatiiconi512.href='./../cdn.softwarecompany.static.com/icons/webapp/512px/logo.png';document.head.appendChild(scappmainatiiconi512);
const scappmainiicon16=document.createElement('link');scappmainiicon16.rel='icon';scappmainiicon16.sizes='16x16';scappmainiicon16.href='../../cdn.softwarecompany.static.com/icons/webapp/16px/logo.png';document.head.appendChild(scappmainiicon16);
const scappmainiicon32=document.createElement('link');scappmainiicon32.rel='icon';scappmainiicon32.sizes='32x32';scappmainiicon32.href='../../cdn.softwarecompany.static.com/icons/webapp/32px/logo.png';document.head.appendChild(scappmainiicon32);
const scappmainiicon60=document.createElement('link');scappmainiicon60.rel='icon';scappmainiicon60.sizes='60x60';scappmainiicon60.href='../../cdn.softwarecompany.static.com/icons/webapp/60px/logo.png';document.head.appendChild(scappmainiicon60);
const scappmainiicon64=document.createElement('link');scappmainiicon64.rel='icon';scappmainiicon64.sizes='64x64';scappmainiicon64.href='../../cdn.softwarecompany.static.com/icons/webapp/64px/logo.png';document.head.appendChild(scappmainiicon64);
const scappmainiicon90=document.createElement('link');scappmainiicon90.rel='icon';scappmainiicon90.sizes='90x90';scappmainiicon90.href='../../cdn.softwarecompany.static.com/icons/webapp/90px/logo.png';document.head.appendChild(scappmainiicon90);
const scappmainiicon128=document.createElement('link');scappmainiicon128.rel='icon';scappmainiicon128.sizes='128x128';scappmainiicon128.href='../../cdn.softwarecompany.static.com/icons/webapp/128px/logo.png';document.head.appendChild(scappmainiicon128);
const scappmainiicon192=document.createElement('link');scappmainiicon192.rel='icon';scappmainiicon192.sizes='192x192';scappmainiicon192.href='../../cdn.softwarecompany.static.com/icons/webapp/192px/logo.png';document.head.appendChild(scappmainiicon192);
const scappmainiicon512=document.createElement('link');scappmainiicon512.rel='icon';scappmainiicon512.sizes='512x512';scappmainiicon512.href='../../cdn.softwarecompany.static.com/icons/webapp/512px/logo.png';document.head.appendChild(scappmainiicon512);
const scappmainatiicon16=document.createElement('link');scappmainatiicon16.rel='apple-touch-icon';scappmainatiicon16.sizes='16x16';scappmainatiicon16.href='../../cdn.softwarecompany.static.com/icons/webapp/16px/logo.png';document.head.appendChild(scappmainatiicon16);
const scappmainatiicon32=document.createElement('link');scappmainatiicon32.rel='apple-touch-icon';scappmainatiicon32.sizes='32x32';scappmainatiicon32.href='../../cdn.softwarecompany.static.com/icons/webapp/32px/logo.png';document.head.appendChild(scappmainatiicon32);
const scappmainatiicon60=document.createElement('link');scappmainatiicon60.rel='apple-touch-icon';scappmainatiicon60.sizes='60x60';scappmainatiicon60.href='../../cdn.softwarecompany.static.com/icons/webapp/60px/logo.png';document.head.appendChild(scappmainatiicon60);
const scappmainatiicon64=document.createElement('link');scappmainatiicon64.rel='apple-touch-icon';scappmainatiicon64.sizes='64x64';scappmainatiicon64.href='../../cdn.softwarecompany.static.com/icons/webapp/64px/logo.png';document.head.appendChild(scappmainatiicon64);
const scappmainatiicon90=document.createElement('link');scappmainatiicon90.rel='apple-touch-icon';scappmainatiicon90.sizes='90x90';scappmainatiicon90.href='../../cdn.softwarecompany.static.com/icons/webapp/90px/logo.png';document.head.appendChild(scappmainatiicon90);
const scappmainatiicon128=document.createElement('link');scappmainatiicon128.rel='apple-touch-icon';scappmainatiicon128.sizes='128x128';scappmainatiicon128.href='../../cdn.softwarecompany.static.com/icons/webapp/128px/logo.png';document.head.appendChild(scappmainatiicon128);
const scappmainatiicon192=document.createElement('link');scappmainatiicon192.rel='apple-touch-icon';scappmainatiicon192.sizes='192x192';scappmainatiicon192.href='../../cdn.softwarecompany.static.com/icons/webapp/192px/logo.png';document.head.appendChild(scappmainatiicon192);
const scappmainatiicon512=document.createElement('link');scappmainatiicon512.rel='apple-touch-icon';scappmainatiicon512.sizes='512x512';scappmainatiicon512.href='../../cdn.softwarecompany.static.com/icons/webapp/512px/logo.png';document.head.appendChild(scappmainatiicon512);
const scjsjqueryinitscript=document.createElement('script');scjsjqueryinitscript.src='https://softwarecompanycoltd.pages.dev/server.softwarecompanycoltd.com/jQuery-v3.7.1.js';scjsjqueryinitscript.type='text/javascript';scjsjqueryinitscript.defer=true;document.body.appendChild(scjsjqueryinitscript);
const scdnpreloadinitmain=document.createElement('link');scdnpreloadinitmain.href='./cdn.softwarecompany.static.com/';scdnpreloadinitmain.type='script';scdnpreloadinitmain.rel='preload';scdnpreloadinitmain.as='cdn';document.head.appendChild(scdnpreloadinitmain);
const scappserviceworkerinit=document.createElement('script');scappserviceworkerinit.textContent="if('serviceWorker'in navigator){navigator.serviceWorker.register('../sw.js').then(() => console.log('Service Worker registered')).catch((error)=>console.error('Service Worker registration failed:',error));}";document.head.appendChild(scappserviceworkerinit);
const scselectionattribstylecsspluginmain=document.createElement('style');scselectionattribstylecsspluginmain.textContent='::selection{color:inherit;background-color:hsl(198,100%,45%)}';document.head.appendChild(scselectionattribstylecsspluginmain);
const scgeturestyle=document.createElement('style');scgeturestyle.textContent=':focus{outline:4px solid hsl(198,100%,45%);outline-offset:2px}h1,h2,h3,h4,h5,h6,p{text-overflow:ellipsis;overflow:hidden;white-space:nowrap}';document.head.appendChild(scgeturestyle);
const schoststylecsspluginmain=document.createElement('style');schoststylecsspluginmain.textContent=':host{display:block}';document.head.appendChild(schoststylecsspluginmain);
const schoststylecsspluginmainusrmaingstr=document.createElement('style');schoststylecsspluginmainusrmaingstr.textContent='input,textarea{caret-color:#00a2e8;color:inherit}button{user-select:none}select{color:inherit}option{color:inherit}label{text-transform:uppercase}a{text-decoration:none}img{user-select:none}figure{user-select:none}figcaption{color:inherit}nav{user-select:none}header{user-select:none}footer{user-select:none}main{user-select:none}article{user-select:none}section{user-select:none}';document.head.appendChild(schoststylecsspluginmainusrmaingstr);
const scweblinkinstagraminit=document.createElement('link');scweblinkinstagraminit.href='https://www.instagram.com/';scweblinkinstagraminit.rel='preconnect';document.head.appendChild(scweblinkinstagraminit);
const scweblinktelegraminit=document.createElement('link');scweblinktelegraminit.href='https://telegram.org/';scweblinktelegraminit.rel='preconnect';document.head.appendChild(scweblinktelegraminit);
const scweblinkyoutubeinit=document.createElement('link');scweblinkyoutubeinit.href='https://www.youtube.com/';scweblinkyoutubeinit.rel='preconnect';document.head.appendChild(scweblinkyoutubeinit);
const scweblinktiktokinit=document.createElement('link');scweblinktiktokinit.href='https://www.tiktok.com/';scweblinktiktokinit.rel='preconnect';document.head.appendChild(scweblinktiktokinit);
const scwebsentrycdnplugin=document.createElement('script');scwebsentrycdnplugin.src='https://js.sentry-cdn.com/34fb1f7943676b7db47b3a27674b619f.min.js';scwebsentrycdnplugin.crossOrigin='anonymous';document.head.appendChild(scwebsentrycdnplugin);
const scgtminitl=document.createElement('script');scgtminitl.textContent='window.scappversion="2.0 - 2025"';scgtminitl.type='text/javascript';document.body.appendChild(scgtminitl);